"""rule unique nulls not distinct

Revision ID: 83ac372491bd
Revises: e0f839d6b483
Create Date: 2026-05-01 19:26:07.142250+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "83ac372491bd"
down_revision: str | None = "e0f839d6b483"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_rate_limit_rules_tier_endpoint"), "rate_limit_rules", type_="unique"
    )
    op.create_unique_constraint(
        "uq_rate_limit_rules_tier_endpoint",
        "rate_limit_rules",
        ["tier", "endpoint"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rate_limit_rules_tier_endpoint", "rate_limit_rules", type_="unique")
    op.create_unique_constraint(
        op.f("uq_rate_limit_rules_tier_endpoint"),
        "rate_limit_rules",
        ["tier", "endpoint"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
