"""initial schema

Revision ID: e0f839d6b483
Revises:
Create Date: 2026-04-26 18:54:20.911758+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e0f839d6b483"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("api_key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tier", sa.Enum("free", "pro", "enterprise", name="client_tier"), nullable=False),
        sa.Column(
            "extra", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("api_key", name=op.f("uq_clients_api_key")),
    )
    op.create_table(
        "rate_limit_rules",
        sa.Column("tier", sa.Enum("free", "pro", "enterprise", name="client_tier"), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column(
            "algorithm",
            sa.Enum(
                "token_bucket",
                "fixed_window",
                "sliding_window_log",
                "leaky_bucket",
                name="algorithm",
            ),
            nullable=False,
        ),
        sa.Column("max_requests", sa.Integer(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_requests > 0", name=op.f("ck_rate_limit_rules_max_requests_positive")
        ),
        sa.CheckConstraint(
            "window_seconds > 0", name=op.f("ck_rate_limit_rules_window_seconds_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_rules")),
        sa.UniqueConstraint("tier", "endpoint", name="uq_rate_limit_rules_tier_endpoint"),
    )
    op.create_table(
        "violations",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "request_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_violations_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rate_limit_rules.id"],
            name=op.f("fk_violations_rule_id_rate_limit_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_violations")),
    )
    op.create_index(op.f("ix_violations_client_id"), "violations", ["client_id"], unique=False)
    op.create_index(op.f("ix_violations_occurred_at"), "violations", ["occurred_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_violations_occurred_at"), table_name="violations")
    op.drop_index(op.f("ix_violations_client_id"), table_name="violations")
    op.drop_table("violations")
    op.drop_table("rate_limit_rules")
    op.drop_table("clients")
    # ### end Alembic commands ###
